services:
  web:
    image: campus-navigation-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Host:Container
    env_file:
      - .env # Load environment variables from .env file
    environment:
      # Variables for Program.cs to build the connection string
      - DB_SERVER=db                     # Service name of the database in Docker network
      - DB_PORT=3306                     # Internal port of the db service
      # ASPNETCORE_ENVIRONMENT, DB_DATABASE, DB_USER, DB_PASSWORD will be loaded from .env by env_file
      # INSTANCE_NAME, APPLICATIONINSIGHTS_CONNECTION_STRING, SQL_CONNECTION_STRING also from .env
      # PORT for ASPNETCORE_URLS will come from .env (defaults to 80 if not set in .env)
      - ASPNETCORE_URLS=http://+:${PORT:-80}
    volumes:
      - ./src/CampusNavigation/wwwroot:/app/wwwroot # For easier static file development (local dev)
    depends_on:
      db:
        condition: service_healthy # Start only after 'db' is healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/diagnostics/dbstatus"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s # Allow time for startup before first check
    restart: unless-stopped

  db:
    image: mariadb:10.6
    command: --default-authentication-plugin=mysql_native_password # For compatibility
    restart: always
    env_file:
      - .env # Load environment variables from .env file
    environment:
      # These will use values from .env through Docker Compose's variable substitution
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3307:3306" # Host:Container
    volumes:
      - mysql-data:/var/lib/mysql # Persist database data
      - ./mysql-init:/docker-entrypoint-initdb.d # Init scripts
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD:-qwe123}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Access via http://localhost:8081
    env_file:
      - .env # Load environment variables from .env file
    environment:
      PMA_HOST: db                        # Connect to the 'db' service
      PMA_PORT: 3306                      # Internal port of the db service
      PMA_USER: ${DB_USER}                # Use DB_USER from .env (e.g., root)
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}   # Use DB_ROOT_PASSWORD from .env
      UPLOAD_LIMIT: 1G                    # Optional: Increase upload limit
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql-data: {} # Named volume for MariaDB data

networks:
  default:
    driver: bridge